[package]
name = "rustistics"
version = "0.1.0"
authors = ["Paul Metcalfe <paul.metcalfe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r-sys = {git="https://github.com/pdmetcalfe/r-sys"}